{% set name = "hdx-python-utilities" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d4a16b1fdd97deafe81e4a2959cab6de4374ea0ccfe76a87c4a7716283398630

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - email_validator
    - frictionless >=5.18.0
    - html5lib
    - loguru
    - pyphonetics
    - python-dateutil >=2.9.0
    - ratelimit
    - requests-file
    - ruamel.yaml
    - xlsx2csv
    # from frictionless[json]
    - ijson >=3.2.3
    - jsonlines >=4.0.0
    # from frictionless[excel]
    - openpyxl >=3.1.2
    - tableschema-to-template >=0.0.13
    - xlrd >=2.0.1
    - xlwt >=1.3.0

test:
  imports:
    - hdx.utilities
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://hdx-python-utilities.readthedocs.io
  summary: |
    A range of helpful utilities for Python developers including streaming
    tabular data, date parsing, JSON and YAML handling, dictionary and list
    utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-utilities.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-utilities

extra:
  recipe-maintainers:
    - kynan
    - mcarans
