{% set name = "hdx-python-utilities" %}
{% set version = "3.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ced6ce557be24d0e209629eae715b181ddc4a02058d9e7a7f1978e73008ead6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - email_validator
    - frictionless >=5.5.1
    - html5lib
    - loguru
    - python-dateutil ==2.8.2
    - ratelimit
    - requests-file
    - ruamel.yaml
    # from frictionless[json]
    - ijson >=3.0
    - jsonlines >=1.2
    # from frictionless[excel]
    - openpyxl >=3.0
    - tableschema-to-template >=0.0.13
    - xlrd >=1.2
    - xlwt >=1.2

test:
  imports:
    - hdx.utilities
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://hdx-python-utilities.readthedocs.io
  summary: |
    A range of helpful utilities for Python developers including streaming
    tabular data, date parsing, JSON and YAML handling, dictionary and list
    utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-utilities.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-utilities

extra:
  recipe-maintainers:
    - kynan
    - mcarans
